name: CSRadrX Fetcher

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

       
      - name: Install dependencies
        run: pnpm install
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

   
      - name: Run fetcher
        run: cd apps/fetcher && pnpm tsx src/aiBlogs.ts
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}